# Generated by Django 3.2.16 on 2022-11-15 20:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passenger1_first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger1_last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger2_first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger2_last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger3_first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger3_last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger4_first_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('passenger4_last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone_number', models.IntegerField()),
                ('registration', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('on_site_status', models.BooleanField(default=True, null=True)),
                ('over_stayed_status', models.BooleanField(default=False, null=True)),
                ('signature', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, null=True, verbose_name='image')),
                ('parking_time_limit', models.DateTimeField(blank=True)),
                ('officers_name', models.CharField(blank=True, default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('test', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
