# Generated by Django 3.2.16 on 2022-11-06 16:40

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('passenger1_first_name', models.CharField(max_length=50)),
                ('passenger1_last_name', models.CharField(max_length=50)),
                ('passenger2_first_name', models.CharField(max_length=50)),
                ('passenger2_last_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('registration', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('time_in', models.DateTimeField(blank=True)),
                ('time_out', models.DateTimeField(blank=True)),
                ('on_site_status', models.BooleanField(default=True)),
                ('over_stayed_status', models.BooleanField(default=False)),
                ('signature', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('parking_time_limit', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('officers_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
