# Generated by Django 3.2.16 on 2022-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='passenger3_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='passenger3_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='passenger4_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='passenger4_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger1_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger1_last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger2_first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger2_last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
