# Generated by Django 3.2.16 on 2022-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0002_alter_accesslog_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='officers_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
