# Generated by Django 3.2.16 on 2022-11-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0003_alter_accesslog_officers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='officers_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(default='', max_length=500),
        ),
    ]
