# Generated by Django 3.2.16 on 2022-11-08 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0003_auto_20221106_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='entry_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
