# Generated by Django 3.2.16 on 2022-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0004_accesslog_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='officers_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
