# Generated by Django 3.2.16 on 2022-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0004_auto_20221115_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
