# Generated by Django 3.2.16 on 2022-11-13 15:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0005_alter_accesslog_officers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='on_site_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='over_stayed_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger1_first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger1_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger2_first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger2_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger3_first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger3_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger4_first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='passenger4_last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
