# Generated by Django 3.2.16 on 2022-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0005_alter_accesslog_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
