# Generated by Django 3.2.16 on 2022-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0006_auto_20221113_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='time_out',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
