# Generated by Django 3.2.16 on 2022-11-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0007_auto_20221119_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='parking_time_limit',
            field=models.TimeField(),
        ),
    ]
