# Generated by Django 3.2.16 on 2022-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0008_alter_accesslog_parking_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='time_in',
            field=models.TimeField(),
        ),
    ]
