# Generated by Django 3.2.16 on 2022-11-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0008_accesslog_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='test',
        ),
    ]
