# Generated by Django 3.2.16 on 2022-11-20 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0009_auto_20221120_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
