# Generated by Django 3.2.16 on 2022-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0009_remove_accesslog_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='time_out',
            field=models.DateTimeField(null=True),
        ),
    ]
