# Generated by Django 3.2.16 on 2022-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0010_alter_accesslog_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='test',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='officers_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
