# Generated by Django 3.2.16 on 2022-11-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0011_auto_20221120_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(max_length=10000),
        ),
    ]
