# Generated by Django 3.2.16 on 2022-11-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0012_alter_accesslog_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
