# Generated by Django 3.2.16 on 2022-11-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0013_auto_20221127_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(max_length=8191, unique=True),
        ),
    ]
