# Generated by Django 3.2.16 on 2022-11-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0014_alter_accesslog_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='over_stayed_status',
        ),
    ]
