# Generated by Django 3.2.16 on 2022-11-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0015_remove_accesslog_over_stayed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(max_length=10000),
        ),
    ]
