# Generated by Django 3.2.16 on 2022-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverylog', '0016_alter_accesslog_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='exit_date',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='over_stayed_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='signature',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
